CSS_modules
Sorokintech/MusicWebAppClone pull request #3
Opened 2022-09-13 19:59 UTC by Sorokintech

HW 3

2022-09-14 06:05 UTC, mrerberg requested changes

2022-09-14 06:05 UTC, mrerberg commented on src/App.js
> +import { BottomPlayer } from './components/bottomPlayer/jsx/bottomPlayer';
А зачем тебе подпапки jsx и css? Это лишняя вложенность и нагромождение

2022-09-14 06:05 UTC, mrerberg commented on src/App.js
> +import StyleCSS from './css/style.module.css'
Просто styles или classes

2022-09-14 06:05 UTC, mrerberg commented on src/App.js
> +              <div className={`${StyleCSS.main__centerBlock} ${StyleCSS.centerBlock}`}>
Для компоновки классов воспользуйся библиотекой 

https://github.com/JedWatson/classnames

2022-09-14 06:05 UTC, mrerberg commented on src/components/bottomPlayer/jsx/bottomPlayer-skeleton.jsx
> +import BottomPlayerCSS from '../css/bottomPlayer.module.css'
Где вертикальные отступы между импортом и компонентом?

2022-09-14 06:05 UTC, mrerberg commented on src/components/bottomPlayer/jsx/bottomPlayer-skeleton.jsx
> +                                    <svg className={BottomPlayerCSS.track__play_svg} alt="music">
Иконки лучше реализовать как компоненты отдельные. Пример

https://github.com/core-ds/icons/blob/master/packages/glyph/src/AScoresCircleMIcon.tsx

2022-09-14 06:05 UTC, mrerberg commented on src/components/bottomPlayer/jsx/bottomPlayer.jsx
> +    if (skeleton) {return <BottomPlayerSkeleton/>}
Форматирование не работает?

2022-09-15 19:01 UTC, Sorokintech commented on src/App.js
> +import { BottomPlayer } from './components/bottomPlayer/jsx/bottomPlayer';
Добавил из-за дублирования страниц. Что есть отдельно jsx и jsx для скелетона. Ну и в целом понятнее ориентироваться, где какие файлы. Читал что это одна из удобных практик, разве нет?

2022-10-05 19:11 UTC, Sorokintech commented on src/App.js
> +import StyleCSS from './css/style.module.css'
Поправил

2022-10-05 19:11 UTC, Sorokintech commented on src/components/bottomPlayer/jsx/bottomPlayer-skeleton.jsx
> +import BottomPlayerCSS from '../css/bottomPlayer.module.css'
Добавил

2022-10-05 19:12 UTC, Sorokintech commented on src/components/bottomPlayer/jsx/bottomPlayer-skeleton.jsx
> +                                    <svg className={BottomPlayerCSS.track__play_svg} alt="music">
Добавил

2022-10-05 19:12 UTC, Sorokintech commented on src/components/bottomPlayer/jsx/bottomPlayer.jsx
> +    if (skeleton) {return <BottomPlayerSkeleton/>}
Нет, чуть позже с ним разберусь(

2022-10-06 07:29 UTC, mrerberg commented on src/App.js
> +import { BottomPlayer } from './components/bottomPlayer/jsx/bottomPlayer';
Ты можешь просто в рамках папки bottomPlayer сделать папку skeleton, туда положить весь код скелетона. Так будет в разы удобнее и понятнее

2022-10-06 07:29 UTC, mrerberg commented on src/App.js
> +import { BottomPlayer } from './components/bottomPlayer/jsx/bottomPlayer';
Скелетон будет приватным компонентом для bottomPlayer

2022-10-31 17:55 UTC, merged