5 7
Sorokintech/MusicWebAppClone pull request #4
Opened 2022-10-05 18:41 UTC by Sorokintech

Домашки 5-7

2022-10-06 07:24 UTC, mrerberg requested changes

2022-10-06 07:24 UTC, mrerberg commented on src/components/navbar/jsx/navbar.jsx
> +    // let classNames = require('classnames/bind');
?

2022-10-06 07:24 UTC, mrerberg commented on src/components/sideBar/jsx/sideBar.jsx
> +// import {require} from 'react';
?

2022-10-06 11:49 UTC, yadimko commented on src/App.js
>      }, [])
?

2022-10-19 06:12 UTC, mrerberg requested changes

2022-10-19 06:12 UTC, mrerberg commented on src/components/navbar/jsx/navbar.jsx
> +    const mainTheme = classNames(
Можно использовать сокращенное имя либы

classNames -> cn и любые другие производные

2022-10-19 06:12 UTC, mrerberg commented on src/components/navbar/jsx/navbar.jsx
> +        styles.main__nav,
Учитывая то, что ты используешь css модули, можно не использовать БЭМ.

nav
navLogo
burger
list

и так далее. И да, все классы есть смысл теперь писать в camelCase

2022-10-22 12:45 UTC, mrerberg requested changes

2022-10-22 12:45 UTC, mrerberg commented on src/components/bottomPlayer/bottomPlayer.jsx
> +    const content = cn(
Эти переменные не нужны, можно писать вызов функции cn прям в классе элемента

```
<div className={cn(...)}>
```

И да, такое количество переменных меня навело на мысль - может есть смысл разбить данный компонент на несколько маленьких?

2022-10-22 12:45 UTC, mrerberg commented on src/components/bottomPlayer/bottomPlayer.jsx
> +export function BottomPlayer({skeleton}) {
Props `skeleton` слишком абстрактно звучит. Мб loading?

2022-10-22 12:45 UTC, mrerberg commented on src/components/bottomPlayer/skeleton/bottomPlayer-skeleton.jsx
> +    const bar = cn(
Не надо классы в переменные. Это же вообще нечитаемо выглядит

2022-10-22 12:45 UTC, mrerberg commented on src/components/trackNav/trackNav.jsx
> +    const buttonGenre = cn(
```
 const buttonGenre = cn(
        styles.button,
        styles.btnText,
{
  [styles.isActive]:   visible.genre,
},
    );
```

Изучай API инструмента, с которым работаешь

2022-10-22 14:06 UTC, Sorokintech commented on src/components/bottomPlayer/skeleton/bottomPlayer-skeleton.jsx
> +    const bar = cn(
Не совсем понял, что имеешь в виду. Что именно аналогичные классу названия? Или в целом классы пихать в переменные. В прошлом коммите именно так и сделал, думал так норм.

2022-10-25 12:03 UTC, Sorokintech commented on src/components/bottomPlayer/skeleton/bottomPlayer-skeleton.jsx
> +    const bar = cn(
Заменил bar  на mainClass

2022-10-25 12:03 UTC, Sorokintech commented on src/components/bottomPlayer/bottomPlayer.jsx
> +export function BottomPlayer({skeleton}) {
Поправил

2022-10-28 06:44 UTC, mrerberg commented on src/components/bottomPlayer/skeleton/bottomPlayer-skeleton.jsx
> +    const bar = cn(
Я про то, что вызов функции cn можно делать прям в атрибуте класса, не нужна переменная. 

Как ты сделал, так редко кто делает и в особых случаях, когда это оправдано

Я про это: 
```
<button className={ cn( ... ) } >
```

2022-10-28 06:46 UTC, mrerberg requested changes

2022-10-28 06:46 UTC, mrerberg commented on src/components/bottomPlayer/skeleton/bottomPlayer-skeleton.jsx
> +    // const bar = cn(
Почему не удалил код?

2022-10-28 06:46 UTC, mrerberg commented on src/components/trackList/skeleton/trackList-skeleton.jsx
> +                            <div className={cn(styles.item)}>
Вообще, ты мог бы только оставить верстку одного item, а остальные - нагенерировать с помощью react и map

2022-10-28 20:54 UTC, Sorokintech commented on src/components/bottomPlayer/skeleton/bottomPlayer-skeleton.jsx
> +    // const bar = cn(
Удалил

2022-10-28 20:54 UTC, Sorokintech commented on src/components/trackList/skeleton/trackList-skeleton.jsx
> +                            <div className={cn(styles.item)}>
Поправил

2022-10-31 06:56 UTC, mrerberg approved these changes

2022-10-31 17:55 UTC, merged